application: app-test-area
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /background
  static_dir: background

- url: /profilepicture
  static_dir: profilepicture

- url: /.*
  script: tripleapp.py
